/** @type {import('tailwindcss').Config} */
// Ported verbatim from the former inline `tailwind.config` that the Tailwind
// Play CDN consumed at runtime. Now compiled to a static dist.css so the page
// ships fully styled on first paint (no flash-of-unstyled-content).
module.exports = {
  content: ['./*.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#474649',
        'surface-container': '#f1edec',
        'on-primary': '#ffffff',
        surface: '#fdf8f7',
        'on-primary-fixed': '#1d1b18',
        'outline-variant': '#cdc5bc',
        'error-container': '#ffdad6',
        'inverse-primary': '#cbc5c0',
        outline: '#7c766e',
        'tertiary-fixed-dim': '#c8c6c8',
        'on-primary-fixed-variant': '#494643',
        'tertiary-fixed': '#e4e2e4',
        'primary-fixed': '#e7e1dc',
        secondary: '#523fde',
        'inverse-surface': '#313030',
        'surface-container-highest': '#e6e2e0',
        'on-secondary-container': '#fffbff',
        'on-tertiary-container': '#858386',
        'surface-container-low': '#f7f3f1',
        'surface-tint': '#615e5a',
        'on-error-container': '#93000a',
        'surface-variant': '#e6e2e0',
        'primary-fixed-dim': '#cbc5c0',
        tertiary: '#000000',
        'on-primary-container': '#87837f',
        'on-background': '#1c1b1b',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#c5c0ff',
        'secondary-fixed': '#e4dfff',
        primary: '#000000',
        'surface-dim': '#ddd9d8',
        'on-secondary': '#ffffff',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#4b463f',
        'tertiary-container': '#1b1b1d',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#3b21c9',
        error: '#ba1a1a',
        'inverse-on-surface': '#f4f0ee',
        'on-secondary-fixed': '#140067',
        background: '#fdf8f7',
        'secondary-container': '#6b5cf8',
        'surface-bright': '#fdf8f7',
        'on-tertiary-fixed': '#1b1b1d',
        'primary-container': '#1d1b18',
        'surface-container-high': '#ebe7e6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        unit: '4px',
        'container-max': '1200px',
        margin: '40px',
      },
      fontFamily: {
        'body-md': ['Hanken Grotesk'],
        'body-lg': ['Hanken Grotesk'],
        'display-lg': ['Hanken Grotesk'],
        'headline-lg': ['Hanken Grotesk'],
        'headline-md': ['Hanken Grotesk'],
        'code-md': ['JetBrains Mono'],
        'label-sm': ['JetBrains Mono'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'code-md': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
}
